#install:
#  - ps: choco install ninja


# it doesn't work !!
# if use ninja, then the default cc is clang (?) but the options emitted
# by cmake are for clang-cl. clang-cl is not installed.
# cmake -G "Visual Studio 15 2017" doesn't work either
#
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..
  - msbuild
