language: c

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/cmake-3.x'

    packages:
      - cmake
      - cmake-data

script: |
   mkdir build 2> /dev/null
   cd build
   cmake ..
   make
